Module 5
js-tasks-ru/jsbasic-20240321_aigulikh pull request #7
Opened 2024-04-18 18:53 UTC by aigulikh

2024-04-18 18:54 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-04-19 17:20 UTC, SinimaWath reviewed
Тут все ок но надо решить добавленные задачи

2024-04-20 10:50 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-20 11:43 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-04-22 09:35 UTC, SinimaWath requested changes
Тут все ок :) есть маленькие замечания и давай дорешаем задачу 7-4

2024-04-22 09:35 UTC, SinimaWath commented on 5-module/2-task/index.js
> +  button.addEventListener('click', function(event) {
Тут можно использовать стрелочную функцию:
```
button.adddEventListener("click", () => {
   let text = document.getElementById("text");
   text.hidden = !text.hidden;
})
```

2024-04-22 09:35 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    cardName.textContent = `${this.product.name}`
Эти значения надо проставить прямо в методе #template:

```
  #template() {
   return `
    <div class="card">
    <div class="card__top">
        <img src="/assets/images/products/${this.product.image}" class="card__image" alt="product">
        <span class="card__price">€${this.product.price.toFixed(2)}</span>
    </div>
    <div class="card__body">
        <div class="card__title">${this.product.name}</div>
        <button type="button" class="card__button">
            <img src="/assets/images/icons/plus-icon.svg" alt="icon">
        </button>
    </div>
</div>`;
  }
```

2024-04-22 19:14 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-22 19:47 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-04-23 17:15 UTC, SinimaWath approved these changes
Все круто!

2024-04-23 17:17 UTC, merged